---
title: "git_01"
author: "Tania Boror"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->


## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

A BOAT beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July --  
Children three that nestle near,  
Eager eye and willing ear,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

A neighbor of mine in the village  
Likes to tell how one spring  
When she was a girl on the farm, she did  
A childlike thing.  

One day she asked her father  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

A neighbor of mine in the village  
Likes to tell how one spring  
When she was a girl on the farm, she did  
A childlike thing.  

One day she asked her father  
To give her a garden plot  
To plant and tend and reap herself,  
And he said, 'Why not?'  

In casting about for a corner  
He thought of an idle bit  
Of walled-off ground where a shop had stood,  
And he said, 'Just it.'  


